"""Forward error correction: the Reed-Solomon code every optical link runs.

A link is not specified at the bit error rate it delivers. It is specified at
the rate its *decoder* delivers, and the gap between the two is the whole reason
a coded system can run at an optical signal-to-noise ratio that would look like
a broken link on an oscilloscope. Every sensitivity figure in this project is
quoted at a pre-FEC threshold; until this module there was nothing behind the
word.

The code is **RS(255, 239) over GF(2^8)**, the "generic FEC" of ITU-T G.709 —
the one carried in the OTN frame overhead and the reference every later optical
code is measured against. It is specified completely enough to implement from
the standard alone:

* the field is GF(2^8) generated by ``x^8 + x^4 + x^3 + x^2 + 1`` (0x11D),
* the code takes 239 information symbols to 255, so 16 parity symbols,
* which corrects up to ``t = 8`` symbol errors anywhere in the codeword,
* at an overhead of ``255/239 - 1``, the 6.69 % an OTN frame spends.

**Why a symbol code and not a bit code.** A Reed-Solomon symbol here is a byte,
and the decoder is indifferent to how many bits inside it are wrong: eight bad
bits in one byte cost the same as one. That is not an accident of the
construction, it is why the code was chosen for a channel whose errors arrive in
bursts — and it is the property that makes the post-decoding rate depend on the
*symbol* error rate rather than the bit error rate, which is where every
closed-form expression below starts.

References: ITU-T G.709/Y.1331, Annex A (the code and its generator polynomial);
E. R. Berlekamp, *Algebraic Coding Theory*, 1968, and J. L. Massey, "Shift
register synthesis and BCH decoding", IEEE Trans. Inf. Theory 15(1), 1969, for
the decoder; G. D. Forney, "On decoding BCH codes", IEEE Trans. Inf. Theory
11(4), 1965, for the error magnitudes.
"""

from __future__ import annotations

import math
from dataclasses import dataclass

import numpy as np

#: The field's primitive polynomial, ``x^8 + x^4 + x^3 + x^2 + 1``, as the
#: coefficient bits of its low eight terms plus the implicit x^8. This is the
#: one G.709 names, and it is not the only primitive polynomial of degree 8 —
#: a different choice gives a different field, a different generator polynomial
#: and codewords that no G.709 decoder would accept.
PRIMITIVE_POLYNOMIAL = 0x11D

#: Symbols in a codeword, information symbols in one, and the resulting
#: correction power. ``t`` is not a free parameter: a Reed-Solomon code meets
#: the Singleton bound with equality, so ``2t = n - k`` exactly and the code
#: corrects half its parity.
CODEWORD_SYMBOLS = 255
MESSAGE_SYMBOLS = 239
PARITY_SYMBOLS = CODEWORD_SYMBOLS - MESSAGE_SYMBOLS
CORRECTABLE_SYMBOLS = PARITY_SYMBOLS // 2

#: The exponent of the first root of the generator polynomial. G.709 uses the
#: consecutive roots ``alpha^0 ... alpha^15``, which is the convention Forney's
#: magnitude formula below is written against; the other common choice, starting
#: at ``alpha^1``, produces a valid code that is simply a different one.
FIRST_ROOT_EXPONENT = 0


def _build_tables() -> tuple[np.ndarray, np.ndarray]:
    """Discrete logarithm and antilogarithm tables for GF(2^8).

    Multiplication in the field is addition of logarithms, which turns every
    inner loop below into table lookups on integer arrays. The antilog table is
    doubled in length so that an exponent sum up to 508 needs no modulo — the
    reduction costs more than the memory does.
    """
    antilog = np.zeros(512, dtype=np.int32)
    log = np.zeros(256, dtype=np.int32)
    value = 1
    for power in range(255):
        antilog[power] = value
        log[value] = power
        value <<= 1
        if value & 0x100:
            value ^= PRIMITIVE_POLYNOMIAL
    antilog[255:510] = antilog[0:255]
    # log[0] is undefined — zero has no logarithm — and is left at 0 so that a
    # lookup on it is arithmetically harmless; every product below masks the
    # zero case explicitly rather than relying on it.
    return log, antilog


_LOG, _ANTILOG = _build_tables()


def gf_multiply(a: np.ndarray | int, b: np.ndarray | int) -> np.ndarray:
    """Multiply in GF(2^8), elementwise, with zero handled explicitly."""
    left = np.asarray(a, dtype=np.int32)
    right = np.asarray(b, dtype=np.int32)
    product = _ANTILOG[_LOG[left] + _LOG[right]]
    return np.where((left == 0) | (right == 0), 0, product).astype(np.int32)


def gf_inverse(a: int) -> int:
    """The multiplicative inverse of a non-zero field element."""
    if a == 0:
        raise ZeroDivisionError("zero has no inverse in a field")
    return int(_ANTILOG[255 - _LOG[a]])


def gf_power(a: int, exponent: int) -> int:
    """``a`` raised to an integer power in GF(2^8)."""
    if a == 0:
        return 0 if exponent != 0 else 1
    return int(_ANTILOG[(_LOG[a] * exponent) % 255])


def _polynomial_multiply(left: np.ndarray, right: np.ndarray) -> np.ndarray:
    """Multiply two polynomials over GF(2^8), coefficients highest power first."""
    result = np.zeros(left.size + right.size - 1, dtype=np.int32)
    for index, coefficient in enumerate(left):
        if coefficient:
            result[index : index + right.size] ^= gf_multiply(right, int(coefficient))
    return result


def generator_polynomial() -> np.ndarray:
    """``g(x) = product (x - alpha^i)`` over the code's consecutive roots.

    Every codeword is a multiple of this polynomial, which is the same thing as
    saying every codeword evaluates to zero at each of its roots. That is the
    only property the decoder actually uses: the syndromes below are those
    evaluations, and they are zero exactly when nothing has gone wrong.
    """
    polynomial = np.array([1], dtype=np.int32)
    for index in range(PARITY_SYMBOLS):
        root = _ANTILOG[(FIRST_ROOT_EXPONENT + index) % 255]
        polynomial = _polynomial_multiply(polynomial, np.array([1, root], dtype=np.int32))
    return polynomial


_GENERATOR = generator_polynomial()


def encode_blocks(messages: np.ndarray) -> np.ndarray:
    """Systematically encode ``(blocks, 239)`` message symbols to ``(blocks, 255)``.

    Systematic means the message appears unchanged in the output and the parity
    is appended, which is what lets a decoder that gives up still hand back the
    data it could not verify — and what makes an uncoded link the same bytes as
    a coded one with the tail cut off.
    """
    messages = np.asarray(messages, dtype=np.int32)
    if messages.ndim != 2 or messages.shape[1] != MESSAGE_SYMBOLS:
        raise ValueError(
            f"expected message blocks of shape (n, {MESSAGE_SYMBOLS}), got {messages.shape}"
        )

    blocks = messages.shape[0]
    remainder = np.zeros((blocks, PARITY_SYMBOLS), dtype=np.int32)
    for position in range(MESSAGE_SYMBOLS):
        feedback = messages[:, position] ^ remainder[:, 0]
        remainder = np.concatenate(
            [remainder[:, 1:], np.zeros((blocks, 1), dtype=np.int32)], axis=1
        )
        active = feedback != 0
        if np.any(active):
            remainder[active] ^= gf_multiply(_GENERATOR[1:][None, :], feedback[active][:, None])
    return np.concatenate([messages, remainder], axis=1)


def _syndromes(received: np.ndarray) -> np.ndarray:
    """Evaluate every received word at each root of the generator polynomial."""
    blocks = received.shape[0]
    syndromes = np.zeros((blocks, PARITY_SYMBOLS), dtype=np.int32)
    for index in range(PARITY_SYMBOLS):
        root = int(_ANTILOG[(FIRST_ROOT_EXPONENT + index) % 255])
        accumulator = np.zeros(blocks, dtype=np.int32)
        for position in range(CODEWORD_SYMBOLS):  # Horner, highest power first
            accumulator = gf_multiply(accumulator, root) ^ received[:, position]
        syndromes[:, index] = accumulator
    return syndromes


def _berlekamp_massey(syndrome: np.ndarray) -> np.ndarray:
    """The shortest linear recurrence that generates ``syndrome``.

    Returns the error-locator polynomial, lowest power first. Its degree is the
    number of errors the decoder believes are present, and its roots are the
    reciprocals of where they are.
    """
    locator = np.array([1], dtype=np.int32)
    previous = np.array([1], dtype=np.int32)
    shift = 1
    last_discrepancy = 1

    for step in range(PARITY_SYMBOLS):
        discrepancy = int(syndrome[step])
        for index in range(1, locator.size):
            discrepancy ^= int(gf_multiply(int(locator[index]), int(syndrome[step - index])))

        if discrepancy == 0:
            shift += 1
            continue

        scale = gf_multiply(discrepancy, gf_inverse(last_discrepancy))
        correction = np.zeros(shift + previous.size, dtype=np.int32)
        correction[shift:] = gf_multiply(previous, scale)

        if correction.size > locator.size:
            padded = np.zeros(correction.size, dtype=np.int32)
            padded[: locator.size] = locator
            updated = padded ^ correction
        else:
            updated = locator.copy()
            updated[: correction.size] ^= correction

        if 2 * (locator.size - 1) <= step:
            previous = locator
            last_discrepancy = discrepancy
            shift = 1
        else:
            shift += 1
        locator = updated

    return locator


def _formal_derivative(polynomial: np.ndarray) -> np.ndarray:
    """``d/dx`` in characteristic two: every even-power term vanishes.

    Not a calculus convenience — Forney's formula needs it, and in a field of
    characteristic two the derivative of ``x^2`` really is zero rather than
    ``2x`` rounded away.
    """
    derivative = np.zeros(max(polynomial.size - 1, 1), dtype=np.int32)
    for power in range(1, polynomial.size):
        if power % 2 == 1:
            derivative[power - 1] = polynomial[power]
    return derivative


def _evaluate(polynomial: np.ndarray, x: int) -> int:
    """Evaluate a polynomial given lowest power first, at a field element."""
    accumulator = 0
    for coefficient in reversed(polynomial):
        accumulator = int(gf_multiply(accumulator, x)) ^ int(coefficient)
    return accumulator


@dataclass(frozen=True)
class DecodeResult:
    """What the decoder did to one batch of codewords."""

    messages: np.ndarray
    """The recovered information symbols, shape ``(blocks, 239)``."""

    corrected: int
    """Symbol errors repaired, summed over every codeword."""

    failed: int
    """Codewords the decoder could not correct.

    A Reed-Solomon decoder does not fail quietly. Past ``t`` errors it either
    finds no consistent error pattern — counted here — or, more rarely, finds a
    wrong one and hands back a codeword that is confidently incorrect. The
    second is a *miscorrection*, it is not detectable from inside the decoder,
    and it is why a coded link is quoted with an output error rate rather than
    with the word "corrected".
    """


def decode_blocks(received: np.ndarray) -> DecodeResult:
    """Correct up to ``t`` symbol errors per codeword and return the messages.

    Syndromes, then Berlekamp-Massey for the error locator, then a Chien search
    for its roots, then Forney for the magnitudes. A codeword whose syndromes
    are all zero is already a codeword and skips every one of those steps, which
    is the ordinary case on a working link and the reason this is affordable.
    """
    received = np.asarray(received, dtype=np.int32).copy()
    if received.ndim != 2 or received.shape[1] != CODEWORD_SYMBOLS:
        raise ValueError(
            f"expected codewords of shape (n, {CODEWORD_SYMBOLS}), got {received.shape}"
        )

    syndromes = _syndromes(received)
    suspect = np.flatnonzero(np.any(syndromes != 0, axis=1))

    corrected = 0
    failed = 0
    for block in suspect:
        locator = _berlekamp_massey(syndromes[block])
        errors = locator.size - 1

        # Chien search: alpha^-position is a root exactly when position is in
        # error. Walking positions rather than field elements keeps the mapping
        # between the two in one place.
        positions = [
            position
            for position in range(CODEWORD_SYMBOLS)
            # The codeword is stored highest power first, so position p holds
            # the coefficient of x^(n-1-p).
            if _evaluate(locator, gf_inverse(gf_power(2, CODEWORD_SYMBOLS - 1 - position))) == 0
        ]
        if errors == 0 or len(positions) != errors:
            failed += 1
            continue

        # Omega(x) = S(x) * Lambda(x) mod x^(2t), the error evaluator.
        evaluator = _polynomial_multiply(syndromes[block][::-1], locator[::-1])[::-1]
        evaluator = evaluator[:PARITY_SYMBOLS]
        derivative = _formal_derivative(locator)

        repaired = True
        for position in positions:
            location = gf_power(2, CODEWORD_SYMBOLS - 1 - position)
            inverse = gf_inverse(location)
            denominator = _evaluate(derivative, inverse)
            if denominator == 0:
                repaired = False
                break
            magnitude = gf_multiply(
                gf_power(location, 1 - FIRST_ROOT_EXPONENT),
                gf_multiply(_evaluate(evaluator, inverse), gf_inverse(denominator)),
            )
            received[block, position] ^= int(magnitude)

        if not repaired or np.any(_syndromes(received[block : block + 1]) != 0):
            failed += 1
            continue
        corrected += len(positions)

    return DecodeResult(messages=received[:, :MESSAGE_SYMBOLS], corrected=corrected, failed=failed)


# ---------------------------------------------------------------------------
# The closed form, which is what the implementation is checked against


def symbol_error_rate(bit_error_rate: float, bits_per_symbol: int = 8) -> float:
    """Probability a byte is wrong, given independent bit errors within it."""
    return 1.0 - (1.0 - bit_error_rate) ** bits_per_symbol


def output_bit_error_rate(input_bit_error_rate: float) -> float:
    """Post-decoding bit error rate, from the standard bounded-distance expression.

    A codeword is decoded wrongly when more than ``t`` of its 255 symbols are in
    error. The usual approximation then assumes such a codeword leaves ``i``
    symbols wrong — the ones that were already wrong — which gives::

        P_s,out = (1/n) * sum_{i=t+1}^{n} i * C(n, i) * p^i * (1-p)^(n-i)

    and a bit rate of ``P_s,out`` scaled by the fraction of bits a wrong byte
    carries. It is an approximation in one direction only: a miscorrecting
    decoder adds up to ``t`` further bad symbols, so the true rate is a little
    worse than this, never better. Quoting the optimistic bound and calling it
    the answer is the standard way to overstate a coding gain, so the direction
    is stated rather than left to be discovered.

    Independent bit errors are assumed. That is exactly the channel this library
    produces — additive noise on independent symbols — and exactly not the
    channel Reed-Solomon was chosen for, which is bursty. On a bursty channel
    this code does better than this expression says.
    """
    if not 0.0 <= input_bit_error_rate <= 1.0:
        raise ValueError(f"a bit error rate must be in [0, 1], got {input_bit_error_rate}")
    if input_bit_error_rate == 0.0:
        return 0.0

    p = symbol_error_rate(input_bit_error_rate)
    n = CODEWORD_SYMBOLS
    total = 0.0
    for i in range(CORRECTABLE_SYMBOLS + 1, n + 1):
        term = math.comb(n, i) * p**i * (1.0 - p) ** (n - i)
        total += i * term
        if term == 0.0 and i > CORRECTABLE_SYMBOLS + 8:
            break  # the tail has underflowed; the remaining terms are smaller
    symbols_out = total / n
    # How much of a wrong byte is wrong. Conditioned on at least one of its
    # eight bits having flipped, the expected number that did is ``8*p/p_s``, so
    # the fraction of the byte in error is ``p/p_s``. For the small p this is
    # used at that is about an eighth — a wrong byte is almost always wrong in
    # exactly one bit — and *not* the half it would tend to if p approached 0.5.
    # Assuming the half instead makes this four times pessimistic at 3e-3, which
    # is what the Monte Carlo comparison in the tests was written to catch and
    # did.
    #
    # The message rate and the codeword rate are the same number here: the i bad
    # symbols of a failed codeword fall uniformly across all 255 positions, so
    # the 239/255 that reach the message cancels against the 239 it is divided
    # by.
    return symbols_out * bit_error_rate_ratio(input_bit_error_rate)


def bit_error_rate_ratio(input_bit_error_rate: float) -> float:
    """Fraction of a symbol that is wrong, given that the symbol is wrong."""
    p = input_bit_error_rate
    p_s = symbol_error_rate(p)
    return p / p_s if p_s > 0.0 else 0.0


def overhead() -> float:
    """Fractional rate cost of the code: 6.69 % for RS(255, 239)."""
    return CODEWORD_SYMBOLS / MESSAGE_SYMBOLS - 1.0
