"""Write the component reference and the Python API page from the code itself.

    python tools/gen_reference_docs.py

The reference is generated, never hand-edited: a component's parameters, units,
bounds and ports already have one source, the class, and a second copy written
by hand is a copy that drifts. ``tests/test_docs.py`` fails when the files in
``docs/`` are not what this script writes, so a new component, or a parameter
whose default moved, cannot ship with a reference that says otherwise.
"""

from __future__ import annotations

import enum
import functools
import inspect
import re
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DOCS = ROOT / "docs"

# The sidebar order of the categories; anything new goes at the end, sorted.
CATEGORY_ORDER = [
    "Electrical Sources",
    "Optical Sources",
    "Electrical",
    "Modulation",
    "Modulators",
    "Fiber",
    "Amplifiers",
    "Passive",
    "Photonic IC",
    "Free Space",
    "Signal Flow",
    "Receivers",
    "DSP",
    "Measurements",
]

# The public API page, section by section, in reading order.
API_SECTIONS = [
    (
        "Building and running a graph",
        ["SimulationContext", "Graph", "Results", "sweep", "SweepResult", "SweepPoint"],
    ),
    ("Project files", ["save", "load"]),
    (
        "The component model",
        ["Component", "Param", "BoolParam", "Port", "PortType", "manifests", "registered_names"],
    ),
    ("Signals and readings", ["OpticalSignal", "Band", "NoiseBin", "PowerReading"]),
    ("Circuits, netlists and PDKs", ["load_pdk", "load_netlist", "circuit_from_netlist"]),
    ("Errors", ["GraphError", "CycleError", "ProjectError", "UnknownComponentError"]),
]

HEADER = "<!-- Generated by tools/gen_reference_docs.py. Do not edit by hand. -->\n"


def _front(title: str, description: str) -> str:
    return f'---\ntitle: "{title}"\ndescription: "{description}"\n---\n\n{HEADER}\n'


def _slug(category: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", category.lower()).strip("-")


def _md(doc: str | None) -> str:
    """A docstring as Markdown: Sphinx roles and reST literals become plain code spans."""
    text = inspect.cleandoc(doc or "")
    text = re.sub(r":[a-z]+:`~?([^`]+)`", r"`\1`", text)
    return text.replace("``", "`")


def _first_line(doc: str | None) -> str:
    return _md(doc).split("\n\n")[0].replace("\n", " ").strip()


def _cell(text: object) -> str:
    return str(text).replace("|", "\\|").replace("\n", " ")


def _param_rows(params: dict) -> list[str]:
    rows = [
        "| Parameter | Default | Unit | Range | Description |",
        "| :--- | :--- | :--- | :--- | :--- |",
    ]
    for name, p in params.items():
        if p.get("choices") is not None:
            rng = "one of " + ", ".join(str(c) for c in p["choices"])
        else:
            lo, hi = p.get("min"), p.get("max")
            rng = (
                ""
                if lo is None and hi is None
                else f"{'' if lo is None else lo} … {'' if hi is None else hi}"
            )
        doc = p.get("doc", "")
        if p.get("applies_when"):
            doc += f" (only when `{p['applies_when']}` is on)"
        unit = "flag" if p.get("type") == "bool" else _cell(p.get("unit", ""))
        rows.append(f"| `{name}` | `{p.get('default')}` | {unit} | {_cell(rng)} | {_cell(doc)} |")
    return rows


def component_pages() -> dict[Path, str]:
    import maiman
    from maiman.registry import lookup

    manifests = maiman.manifests()
    by_cat: dict[str, list[str]] = defaultdict(list)
    for name, m in manifests.items():
        by_cat[m["category"]].append(name)
    cats = [c for c in CATEGORY_ORDER if c in by_cat] + sorted(set(by_cat) - set(CATEGORY_ORDER))

    pages: dict[Path, str] = {}
    index = [
        _front("maiman.components", f"Reference for all {len(manifests)} components, by category."),
        "# maiman.components\n",
        f"Every block the studio's palette offers, {len(manifests)} of them, generated from "
        "the "
        "classes themselves. A component is a pure function of its inputs and its parameters, "
        "and its ports are typed (optical, electrical, binary, symbol, soft or metric), so a "
        "wire between two different types is refused while it is being drawn.\n",
    ]
    for cat in cats:
        index.append(f"## {cat}\n")
        index.append("| Block | Class | What it does | Parameters |")
        index.append("| :--- | :--- | :--- | ---: |")
        for name in sorted(by_cat[cat], key=lambda n: manifests[n]["name"].lower()):
            m = manifests[name]
            cls = lookup(name)
            summary = _first_line(cls.__doc__)
            index.append(
                f"| [{m['name']}]({name}.md) | `{name}` | {_cell(summary)} "
                f"| {len(m['parameters'])} |"
            )
            pages[DOCS / "components" / f"{name}.md"] = _component_page(name, m, cls)
        index.append("")
    pages[DOCS / "components" / "index.md"] = "\n".join(index)
    return pages


def _component_page(name: str, m: dict, cls: type) -> str:
    doc = _md(cls.__doc__)
    out = [
        _front(m["name"], _first_line(cls.__doc__).replace('"', "'")),
        f"# {m['name']}\n",
        f"`maiman.components.{name}` · category **{m['category']}** · [all components](index.md)\n",
        doc,
        "",
        "## Ports\n",
        "| Port | Direction | Type |",
        "| :--- | :--- | :--- |",
    ]
    for direction in ("inputs", "outputs"):
        for port, typ in m["ports"][direction].items():
            out.append(f"| `{port}` | {direction[:-1]} | {typ} |")
    out.append("")
    if m["parameters"]:
        out += ["## Parameters\n", *_param_rows(m["parameters"]), ""]
    if m.get("structural"):
        out += [
            "## Constructor arguments\n",
            "Set when the block is created, not swept: "
            + ", ".join(f"`{k}`" for k in m["structural"])
            + ".",
            "",
        ]
    return "\n".join(out)


def api_page() -> str:
    import maiman

    out = [
        _front("maiman", "The Python API: graphs, runs, sweeps, project files and signals."),
        "# maiman\n",
        "The public surface is deliberately small: if a feature is not reachable from here, "
        "it does not exist. Generated from the docstrings.\n",
    ]
    for title, names in API_SECTIONS:
        out.append(f"## {title}\n")
        for n in names:
            obj = getattr(maiman, n)
            kind = (
                "exception"
                if isinstance(obj, type) and issubclass(obj, BaseException)
                else ("class" if isinstance(obj, type) else "function")
            )
            out.append(f"### `maiman.{n}`\n")
            try:
                sig = str(inspect.signature(obj)).replace("'", "")
            except (TypeError, ValueError):
                sig = ""
            if isinstance(obj, type) and issubclass(obj, enum.Enum):
                # An enum's constructor signature differs between Python versions and
                # says nothing a reader wants; its members are the interface.
                sig = ""
                out += [f"- `{n}.{m.name}`" for m in obj] + [""]
            if kind != "exception" and sig:
                out += [
                    "```python",
                    f"{kind} {n}{sig}" if kind == "class" else f"{n}{sig}",
                    "```",
                    "",
                ]
            out.append(_md(obj.__doc__) + "\n")
            if kind == "class" and not issubclass(obj, BaseException):
                members = []
                for mname, member in inspect.getmembers(obj):
                    raw = obj.__dict__.get(mname)
                    # Methods and properties only: a class attribute holding a value
                    # would print the docstring of the value's type.
                    documented = inspect.isfunction(raw) or isinstance(
                        raw, (property, classmethod, staticmethod, functools.cached_property)
                    )
                    if mname.startswith("_") or not documented:
                        continue
                    first = _first_line(getattr(member, "__doc__", None))
                    if first:
                        members.append(f"- `{mname}` — {first}")
                if members:
                    out += [*members, ""]
    return "\n".join(out)


def generated() -> dict[Path, str]:
    pages = component_pages()
    pages[DOCS / "api.md"] = api_page()
    return {p: text.rstrip() + "\n" for p, text in pages.items()}


def main() -> None:
    sys.path.insert(0, str(ROOT / "src"))
    pages = generated()
    comp = DOCS / "components"
    comp.mkdir(exist_ok=True)
    for stale in comp.glob("*.md"):
        if stale not in pages:
            stale.unlink()
    for path, text in pages.items():
        path.write_text(text, encoding="utf-8")
    print(f"wrote {len(pages)} pages")


if __name__ == "__main__":
    main()
